# Generated by Django 5.2.6 on 2025-09-25 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplylisting',
            name='quality_score',
            field=models.FloatField(default=0.0),
        ),
    ]
