# Generated by Django 5.2.6 on 2025-10-12 07:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_add_starting_price_and_seed_commodities'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='ai_bid_confidence',
            field=models.FloatField(default=0.0, help_text='AI confidence in bid success (0-1)'),
        ),
        migrations.AddField(
            model_name='bid',
            name='ai_bid_strategy',
            field=models.CharField(choices=[('AGGRESSIVE', 'Aggressive'), ('CONSERVATIVE', 'Conservative'), ('OPTIMAL', 'Optimal'), ('SNIPE', 'Last-minute snipe')], default='OPTIMAL', max_length=20),
        ),
        migrations.AddField(
            model_name='bid',
            name='ai_success_probability',
            field=models.FloatField(default=0.0, help_text='AI-calculated success probability'),
        ),
        migrations.AddField(
            model_name='commodity',
            name='demand_score',
            field=models.FloatField(default=0.5, help_text='AI-calculated demand score (0-1)'),
        ),
        migrations.AddField(
            model_name='commodity',
            name='price_trend',
            field=models.CharField(choices=[('RISING', 'Rising'), ('FALLING', 'Falling'), ('STABLE', 'Stable'), ('VOLATILE', 'Volatile')], default='STABLE', max_length=20),
        ),
        migrations.AddField(
            model_name='commodity',
            name='supply_score',
            field=models.FloatField(default=0.5, help_text='AI-calculated supply score (0-1)'),
        ),
        migrations.AddField(
            model_name='commodity',
            name='volatility_index',
            field=models.FloatField(default=0.1, help_text='Price volatility (0-1)'),
        ),
        migrations.AddField(
            model_name='supplylisting',
            name='ai_competitiveness_score',
            field=models.FloatField(default=0.0, help_text='AI score for listing competitiveness (0-1)'),
        ),
        migrations.AddField(
            model_name='supplylisting',
            name='ai_fraud_risk',
            field=models.FloatField(default=0.0, help_text='AI-calculated fraud risk (0-1)'),
        ),
        migrations.AddField(
            model_name='supplylisting',
            name='ai_quality_analysis',
            field=models.JSONField(blank=True, default=dict, help_text='AI analysis of image quality'),
        ),
        migrations.AddField(
            model_name='supplylisting',
            name='ai_suggested_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='supplylisting',
            name='interest_score',
            field=models.FloatField(default=0.0, help_text='AI-calculated buyer interest score'),
        ),
        migrations.AddField(
            model_name='supplylisting',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ai_behavior_score',
            field=models.FloatField(default=0.5, help_text='AI-calculated behavior pattern score'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ai_success_rate',
            field=models.FloatField(default=0.0, help_text='AI-calculated transaction success rate'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ai_trust_score',
            field=models.FloatField(default=0.5, help_text='AI-calculated user trustworthiness (0-1)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_bid_strategy',
            field=models.CharField(choices=[('AGGRESSIVE', 'Aggressive'), ('CONSERVATIVE', 'Conservative'), ('OPTIMAL', 'Optimal'), ('SNIPE', 'Last-minute snipe')], default='OPTIMAL', max_length=20),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('BID_PLACED', 'Bid Placed'), ('BID_OUTBID', 'Bid Outbid'), ('AUCTION_ENDING', 'Auction Ending Soon'), ('AUCTION_WON', 'Auction Won'), ('AUCTION_LOST', 'Auction Lost'), ('PRICE_ALERT', 'Price Alert'), ('NEW_LISTING', 'New Listing Match'), ('AI_INSIGHT', 'AI Market Insight')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marketplace.bid')),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marketplace.supplylisting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_type', models.CharField(choices=[('BID_NOW', 'Bid Now'), ('WATCH', 'Watch'), ('AVOID', 'Avoid'), ('SNIPE', 'Last-minute Bid'), ('HIGH_VALUE', 'High Value Opportunity')], max_length=30)),
                ('confidence_score', models.FloatField(default=0.0, help_text='AI confidence in recommendation (0-1)')),
                ('reason', models.TextField(help_text='AI explanation for recommendation')),
                ('suggested_bid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_recommendations', to='marketplace.supplylisting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-confidence_score'],
                'unique_together': {('user', 'listing')},
            },
        ),
        migrations.CreateModel(
            name='MarketAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('average_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_volatility', models.FloatField(default=0.0)),
                ('demand_trend', models.CharField(choices=[('INCREASING', 'Increasing'), ('DECREASING', 'Decreasing'), ('STABLE', 'Stable')], max_length=20)),
                ('supply_level', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], max_length=20)),
                ('predicted_price_7d', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('predicted_price_30d', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('market_sentiment', models.CharField(choices=[('BULLISH', 'Bullish'), ('BEARISH', 'Bearish'), ('NEUTRAL', 'Neutral')], default='NEUTRAL', max_length=20)),
                ('best_buy_time', models.CharField(default='Anytime', max_length=50)),
                ('optimal_bid_range', models.JSONField(default=dict)),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='marketplace.commodity')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('commodity', 'date')},
            },
        ),
    ]
