# Generated by Django 4.2.7 on 2025-09-02 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('location_type', models.CharField(choices=[('bin', 'Waste Bin'), ('collection_point', 'Collection Point'), ('depot', 'Depot'), ('landfill', 'Landfill')], max_length=50)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('estimated_waste_volume', models.DecimalField(decimal_places=2, default=0, help_text='Estimated waste volume in liters', max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'locations',
            },
        ),
        migrations.CreateModel(
            name='OptimizedRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_name', models.CharField(max_length=200)),
                ('total_distance', models.DecimalField(decimal_places=2, help_text='Total distance in kilometers', max_digits=8)),
                ('total_duration', models.IntegerField(help_text='Total duration in minutes')),
                ('estimated_fuel_consumption', models.DecimalField(decimal_places=2, help_text='Estimated fuel consumption in liters', max_digits=6)),
                ('total_waste_volume', models.DecimalField(decimal_places=2, help_text='Total waste volume in liters', max_digits=8)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'optimized_routes',
            },
        ),
        migrations.CreateModel(
            name='RouteOptimizationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.CharField(max_length=200)),
                ('algorithm_used', models.CharField(max_length=100)),
                ('parameters', models.JSONField(default=dict)),
                ('execution_time', models.DecimalField(decimal_places=3, help_text='Execution time in seconds', max_digits=8)),
                ('optimization_score', models.DecimalField(decimal_places=2, help_text='Optimization quality score (0-100)', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'route_optimization_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('vehicle_type', models.CharField(choices=[('truck', 'Truck'), ('van', 'Van'), ('tractor', 'Tractor'), ('compactor', 'Compactor')], max_length=50)),
                ('capacity', models.DecimalField(decimal_places=2, help_text='Capacity in liters', max_digits=8)),
                ('fuel_efficiency', models.DecimalField(decimal_places=2, help_text='Fuel efficiency in km/l', max_digits=5)),
                ('current_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('current_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'vehicles',
                'indexes': [models.Index(fields=['vehicle_type', 'is_available'], name='vehicles_vehicle_95df6c_idx')],
            },
        ),
        migrations.CreateModel(
            name='RouteLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_order', models.PositiveIntegerField()),
                ('estimated_arrival_time', models.TimeField()),
                ('estimated_departure_time', models.TimeField()),
                ('estimated_waste_collected', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='route_optimizer.location')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='route_optimizer.optimizedroute')),
            ],
            options={
                'db_table': 'route_locations',
                'ordering': ['visit_order'],
            },
        ),
        migrations.AddField(
            model_name='optimizedroute',
            name='locations',
            field=models.ManyToManyField(through='route_optimizer.RouteLocation', to='route_optimizer.location'),
        ),
        migrations.AddField(
            model_name='optimizedroute',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='route_optimizer.vehicle'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['location_type', 'is_active'], name='locations_locatio_439c44_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['priority'], name='locations_priorit_07d0ec_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='routelocation',
            unique_together={('route', 'location')},
        ),
        migrations.AddIndex(
            model_name='optimizedroute',
            index=models.Index(fields=['status', 'created_at'], name='optimized_r_status_30796c_idx'),
        ),
    ]
