# Generated by Django 4.2.7 on 2025-12-05 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route_optimizer', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='fuel_tank_capacity',
            field=models.DecimalField(decimal_places=2, default=100.0, help_text='Fuel tank capacity in liters', max_digits=6),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='capacity',
            field=models.DecimalField(decimal_places=2, help_text='Waste capacity in liters', max_digits=10),
        ),
    ]
