# Generated by Django 5.2.6 on 2025-09-25 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_alter_supplylisting_quality_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplylisting',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='listings/'),
        ),
    ]
